/**
 * AmbientBackground — looping low-contrast ASCII video overlay for empty states.
 * Drop it as a positioned child inside an empty-state container and the foreground
 * text will sit on top of a slowly-drifting phosphor texture.
 *
 * The MP4 is generated by the Hermes ascii-video skill and lives at
 * /ascii_ambient.mp4 (FastAPI serves dashboard/dist/ statically — the file is
 * not API-gated since paths outside /api/* are public).
 */
export default function AmbientBackground({ opacity = 0.35 }: { opacity?: number }) {
  return (
    <div className="absolute inset-0 pointer-events-none overflow-hidden">
      <video
        src="/ascii_ambient.mp4"
        autoPlay
        loop
        muted
        playsInline
        preload="auto"
        className="absolute inset-0 w-full h-full object-cover"
        style={{ opacity }}
      />
      {/* Mask the bright pixels with a soft dark gradient so foreground text stays readable */}
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse at center, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0.7) 80%)",
        }}
      />
    </div>
  );
}
